# Generated by Django 3.2.5 on 2021-08-01 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('stage', models.CharField(choices=[('Documents', 'Aguardando assinatura de documentos'), ('Resources', 'Aguardando transferência de recursos'), ('Management', 'Gestão de patrimônio ativa')], max_length=255)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
    ]
